"""Le 2e corpus, l'anti-triche (§11.1) : 80 messages écrits AVANT les règles du détecteur, avec des marques, des
tournures et des domaines qui n'apparaissent ni dans le corpus principal ni dans la liste des marques du détecteur
(GLS, FedEx, Relais Colis, Cdiscount, Shein, Spotify, Disney+, Booking, Airbnb, Lydia, URSSAF, MaPrimeRénov',
fourrière, chèque énergie, Navigo, Crous, Nickel, Qonto…). Il mesure si les règles généralisent.
"""

from __future__ import annotations

from typing import Any

from tests.corpus_arnaques.donnees import mail, ok

ARNAQUES_INEDITES: list[tuple[str, str, str, Any]] = [
    (
        "n-colis-01",
        "sms",
        "colis",
        "GLS : livraison impossible, numéro de rue manquant. Complétez votre adresse (0,49€ de frais) : https://gls-redelivery.shop/fr",
    ),
    (
        "n-colis-02",
        "sms",
        "colis",
        "FedEx : votre paquet est retenu au hub de Roissy. Taxe d'importation de 3,20€ due : https://s.id/fedex-tax",
    ),
    (
        "n-colis-03",
        "sms",
        "colis",
        "Relais Colis : votre retrait expire aujourd'hui. Prolongez la garde pour 1€ : https://relaiscolis-prolongation.club",
    ),
    (
        "n-colis-04",
        "mail",
        "colis",
        mail(
            '"Cdiscount Livraison" <suivi@cdiscount-expedition.net>',
            "Votre commande ne peut pas être expédiée",
            "Bonjour,\nVotre commande n°CD-77120 est en attente : le transporteur réclame 2,85 € de supplément de poids.\nRégler le supplément : {0}",
            [("Régler maintenant", "https://cdiscount-expedition.net/supp")],
        ),
    ),
    (
        "n-colis-05",
        "sms",
        "colis",
        "Shein : votre colis gratuit (valeur 150€) vous attend, il suffit de payer l'envoi 1,95€ : https://t.ly/sheinfree",
    ),
    (
        "n-colis-06",
        "sms",
        "colis",
        "Votre livreur n'a pas trouvé votre logement. Indiquez un créneau et validez les frais de 1,49€ sur https://redelivery-fr.site",
    ),
    (
        "n-colis-07",
        "sms",
        "colis",
        "Avis de passage : un paquet recommandé vous attend. Programmez une nouvelle présentation avant 20h : urlz.fr/nPq",
    ),
    (
        "n-amende-01",
        "sms",
        "amende",
        "Fourrière municipale : votre véhicule va être enlevé demain matin. Payez la redevance de 17€ pour l'éviter : https://fourriere-paiement.vip",
    ),
    (
        "n-amende-02",
        "sms",
        "amende",
        "Votre permis de conduire va être suspendu : solde de points à 0. Évitez la suspension en réglant 89€ de stage : https://points-permis-regularisation.com",
    ),
    (
        "n-amende-03",
        "sms",
        "amende",
        "Île-de-France Mobilités : contravention non payée pour défaut de titre de transport, 50€ majorés à 180€ sous 48h : https://idfm-amendes.cc",
    ),
    (
        "n-amende-04",
        "mail",
        "amende",
        mail(
            '"Trésor Public - Recouvrement" <recouvrement@tresor-amende.org>',
            "Mise en demeure avant saisie",
            "Madame, Monsieur,\nVous faites l'objet d'une procédure de recouvrement pour une amende impayée de 135 €. Sans paiement sous 24 heures, un huissier procédera à la saisie de votre compte.\nPayer : {0}",
            [("Paiement en ligne", "https://tresor-amende.org/payer")],
        ),
    ),
    (
        "n-amende-05",
        "sms",
        "amende",
        "Autoroute : passage non réglé détecté au péage de Saint-Selve. Réglez 4,30€ maintenant pour éviter 90€ d'indemnité : https://a63-telepeage.me",
    ),
    (
        "n-sante-01",
        "sms",
        "sante",
        "Mon Espace Santé : votre dossier médical sera fermé si vous ne confirmez pas votre identité aujourd'hui : https://monespacesante-verif.site",
    ),
    (
        "n-sante-02",
        "mail",
        "sante",
        mail(
            '"MGEN" <adherent@mgen-remboursements.net>',
            "Trop-perçu de cotisations",
            "Bonjour,\nUn trop-perçu de 96,40 € a été constaté sur vos cotisations. Pour le récupérer, indiquez votre IBAN et les 16 chiffres de votre carte : {0}",
            [("Récupérer 96,40 €", "https://mgen-remboursements.net/iban")],
        ),
    ),
    (
        "n-sante-03",
        "sms",
        "sante",
        "Pharmacie en ligne : votre ordonnance est bloquée, réglez 2€ de frais de validation : https://ordo-validation.shop",
    ),
    (
        "n-sante-04",
        "sms",
        "sante",
        "Votre attestation de mutuelle expire. Sans renouvellement aujourd'hui vos soins ne seront plus pris en charge : https://mutuelle-attestation.club",
    ),
    (
        "n-impots-01",
        "sms",
        "impots",
        "URSSAF : une régularisation de 318€ est en votre faveur. Saisissez vos coordonnées bancaires pour le versement : https://urssaf-regularisation.online",
    ),
    (
        "n-impots-02",
        "mail",
        "impots",
        mail(
            '"MaPrimeRénov\'" <dossier@maprimerenov-validation.com>',
            "Votre aide de 3 200 € est accordée",
            "Félicitations, votre dossier MaPrimeRénov' est validé. Pour déclencher le versement de 3 200 €, réglez les frais de dossier de 9,90 € : {0}",
            [("Débloquer mon aide", "https://maprimerenov-validation.com/frais")],
        ),
    ),
    (
        "n-impots-03",
        "sms",
        "impots",
        "Chèque énergie : 150€ vous sont attribués. Activez-le avant ce soir sinon il sera annulé : https://cheque-energie-activation.site",
    ),
    (
        "n-impots-04",
        "sms",
        "impots",
        "Taxe foncière : un remboursement exceptionnel de 205€ est disponible pour votre logement, confirmez vos infos : https://lc.cx/foncier",
    ),
    (
        "n-banque-01",
        "sms",
        "banque",
        "Nickel : votre compte est restreint suite à un contrôle. Rétablissez l'accès en vous identifiant : https://nickel-acces.net/login",
    ),
    (
        "n-banque-02",
        "sms",
        "banque",
        "Qonto : paiement de 1 150€ en attente de validation. Si ce n'est pas vous, appelez immédiatement le 01 85 39 77 12",
    ),
    (
        "n-banque-03",
        "sms",
        "banque",
        "Lydia : vous avez reçu 80€ de Sarah. Pour les accepter, saisissez votre carte : https://lydia-recevoir.app",
    ),
    (
        "n-banque-04",
        "sms",
        "banque",
        "Votre conseillère du service sécurité : pour bloquer la fraude en cours, lisez-moi le code que vous allez recevoir par SMS.",
    ),
    (
        "n-banque-05",
        "mail",
        "banque",
        mail(
            '"Sécurité Wero" <alerte@wero-securite.com>',
            "Activité suspecte",
            "Bonjour,\nUne tentative de paiement de 489 € a été bloquée. Pour sécuriser votre compte, confirmez vos identifiants bancaires : {0}",
            [("Sécuriser", "https://wero-securite.com/verif")],
        ),
    ),
    (
        "n-banque-06",
        "sms",
        "banque",
        "Un coursier va passer chez vous récupérer votre carte bancaire compromise pour la remplacer. Préparez-la avec votre code dans une enveloppe.",
    ),
    (
        "n-proche-01",
        "sms",
        "proche",
        "Coucou tonton, c'est Léa, j'ai un nouveau portable. Je peux te demander un petit service ? C'est assez pressé",
    ),
    (
        "n-proche-02",
        "sms",
        "proche",
        "Hey c'est moi ta fille, je t'écris d'un numéro prêté, peux-tu régler un achat de 380€ pour moi via le lien que je vais t'envoyer ?",
    ),
    (
        "n-proche-03",
        "sms",
        "proche",
        "Bonjour grand-père, c'est ton petit-fils. J'ai eu un accident, j'ai besoin de 900€ tout de suite pour l'hôpital, n'en parle pas aux parents.",
    ),
    (
        "n-annonce-01",
        "sms",
        "annonce",
        "Bonjour, votre appartement sur Airbnb m'intéresse mais je préfère payer directement par virement, envoyez-moi votre IBAN et je règle la caution de 600€.",
    ),
    (
        "n-annonce-02",
        "mail",
        "annonce",
        mail(
            '"Booking.com" <reservation@booking-confirmation-hotel.com>',
            "Votre réservation sera annulée",
            "Bonjour,\nVotre carte n'a pas pu être vérifiée pour votre séjour du 18/10. Sans vérification sous 12 heures, la réservation sera annulée.\nVérifier ma carte : {0}",
            [("Vérifier", "https://booking-confirmation-hotel.com/verif")],
        ),
    ),
    (
        "n-annonce-03",
        "sms",
        "annonce",
        "Bonjour, j'achète votre vélo 400€. Mon notaire va vous envoyer un chèque de 1 400€, merci de me rembourser la différence par virement.",
    ),
    (
        "n-annonce-04",
        "sms",
        "annonce",
        "Votre billet de concert revendu sur notre plateforme : pour toucher 120€, validez votre compte vendeur : https://billets-revente.vip/vendeur",
    ),
    (
        "n-support-01",
        "sms",
        "support",
        "Spotify : impossible de renouveler votre abonnement Premium. Mettez à jour votre carte pour ne pas perdre vos playlists : https://spotify-renew.site",
    ),
    (
        "n-support-02",
        "mail",
        "support",
        mail(
            '"Disney+" <compte@disneyplus-billing.net>',
            "Votre compte sera fermé",
            "Bonjour,\nNous n'avons pas pu prélever votre abonnement. Votre compte sera fermé sous 24 h. Mettez à jour vos informations : {0}",
            [("disneyplus.com/compte", "https://disneyplus-billing.net/compte")],
        ),
    ),
    (
        "n-support-03",
        "sms",
        "support",
        "Canal+ : offre fidélité, votre abonnement à 1€ par mois à vie ! Activez-la avant minuit : https://canal-fidelite.club",
    ),
    (
        "n-support-04",
        "mail",
        "support",
        mail(
            '"Support Technique" <alerte@pc-protection-24.net>',
            "Votre ordinateur est bloqué",
            "ALERTE : des logiciels espions ont été détectés. Votre ordinateur est bloqué. Ne l'éteignez pas et appelez nos techniciens au 01 70 61 22 98 immédiatement.",
            [],
        ),
    ),
    (
        "n-support-05",
        "sms",
        "support",
        "Veolia : votre facture d'eau est impayée, coupure prévue demain 8h. Régularisez 47,30€ : https://eau-coupure-paiement.net",
    ),
    (
        "n-support-06",
        "sms",
        "support",
        "TotalEnergies : remboursement de 86€ suite à une baisse des tarifs, à demander avant le 15 : https://total-remboursement.site",
    ),
    (
        "n-divers-01",
        "sms",
        "loterie",
        "Votre opérateur vous offre un Samsung Galaxy pour vos 10 ans de fidélité. Réglez 2€ de livraison : https://cadeau-fidelite.vip",
    ),
    (
        "n-divers-02",
        "mail",
        "crypto",
        mail(
            '"Patrimoine Expert" <conseil@livret-plus-garanti.com>',
            "Placement à 9 % sans risque",
            "Bonjour,\nNotre livret exclusif rapporte 9 % par an, capital garanti. Seulement 20 places, ouverture avant demain.\nOuvrir mon livret : {0}",
            [("Ouvrir", "https://livret-plus-garanti.com/ouvrir")],
        ),
    ),
    (
        "n-divers-03",
        "sms",
        "emploi",
        "Recrutement : évaluez des produits en ligne 1h par jour, 120€ versés chaque jour. Ajoutez-moi sur WhatsApp : wa.me/447700900456",
    ),
    (
        "n-divers-04",
        "mail",
        "sextorsion",
        mail(
            '"Inconnu" <noreply.x@outlook.com>',
            "Dernier avertissement",
            "Je vous observe depuis des mois grâce à un logiciel installé sur votre téléphone. J'ai des vidéos intimes. Versez 700 € en Bitcoin sous 48 h, sinon tout sera envoyé à votre famille.",
            [],
        ),
    ),
    ("n-divers-05", "sms", "surtaxe", "Votre colis ne peut être livré, contactez notre service au 08 99 70 41 22."),
    (
        "n-divers-06",
        "sms",
        "crypto",
        "Votre compte d'investissement a généré 2 300€. Pour débloquer le retrait, réglez les frais de déblocage de 180€ : https://retrait-gains.cc",
    ),
    (
        "n-divers-07",
        "sms",
        "annonce",
        "Crous : remboursement de votre caution de 350€ disponible. Confirmez vos coordonnées bancaires : https://crous-caution.site",
    ),
    (
        "n-divers-08",
        "sms",
        "amende",
        "Navigo : votre passe sera désactivé demain suite à un défaut de paiement. Régularisez 86,40€ : https://navigo-regularisation.me",
    ),
    (
        "n-divers-09",
        "sms",
        "support",
        "Votre abonnement antivirus a été renouvelé pour 399,99€. Pour annuler et être remboursé, appelez le 01 89 71 23 40 sous 24h.",
    ),
]

LEGITIMES_INEDITS: list[tuple[str, str, str, Any]] = [
    (
        "n-leg-01",
        "sms",
        "livraison",
        "GLS : votre colis sera livré demain. Suivi : https://gls-group.eu/FR/fr/suivi-colis?match=12345678",
    ),
    (
        "n-leg-02",
        "sms",
        "livraison",
        "FedEx : votre colis 7730 1234 5678 est en cours de livraison. https://www.fedex.com/fr-fr/tracking.html",
    ),
    (
        "n-leg-03",
        "sms",
        "livraison",
        "Relais Colis : votre colis est disponible chez votre commerçant jusqu'au 16/10. Code de retrait 5521.",
    ),
    (
        "n-leg-04",
        "mail",
        "commande",
        mail(
            '"Cdiscount" <commande@cdiscount.com>',
            "Votre commande est expédiée",
            "Bonjour,\nVotre commande CD-55120 a été expédiée. Suivi dans votre espace client : {0}",
            [("Mon compte", "https://www.cdiscount.com/compte")],
            auth=ok("cdiscount.com"),
        ),
    ),
    (
        "n-leg-05",
        "mail",
        "commande",
        mail(
            '"Spotify" <no-reply@spotify.com>',
            "Votre reçu Spotify",
            "Merci ! Votre abonnement Premium (11,12 €) a été renouvelé. Gérer votre abonnement sur {0}.",
            [("spotify.com/account", "https://www.spotify.com/fr/account/")],
            auth=ok("spotify.com"),
        ),
    ),
    (
        "n-leg-06",
        "mail",
        "commande",
        mail(
            '"Booking.com" <noreply@booking.com>',
            "Votre réservation est confirmée",
            "Votre réservation à Arcachon du 18 au 20 octobre est confirmée. Le paiement s'effectuera à l'établissement.",
            [],
            auth=ok("booking.com"),
        ),
    ),
    (
        "n-leg-07",
        "mail",
        "commande",
        mail(
            '"Airbnb" <automated@airbnb.com>',
            "Message de votre hôte",
            "Votre hôte vous a envoyé un message : « Bonjour, la boîte à clés est à gauche de la porte. Bon séjour ! » Répondez dans l'application Airbnb.",
            [],
            auth=ok("airbnb.com"),
        ),
    ),
    (
        "n-leg-08",
        "sms",
        "banque",
        "Lydia : Paul vous a envoyé 15,00€ pour « ciné ». L'argent est sur votre compte Lydia.",
    ),
    (
        "n-leg-09",
        "mail",
        "officiel",
        mail(
            '"Urssaf" <ne-pas-repondre@urssaf.fr>',
            "Votre attestation est disponible",
            "Bonjour,\nVotre attestation de vigilance est disponible dans votre espace en ligne sur urssaf.fr.",
            [],
            auth=ok("urssaf.fr"),
        ),
    ),
    (
        "n-leg-10",
        "mail",
        "commande",
        mail(
            '"OUIGO" <ne-pas-repondre@ouigo.com>',
            "Votre billet OUIGO",
            "Votre billet Bordeaux - Paris du 22/10 est disponible dans l'application SNCF Connect. Bon voyage !",
            [],
            auth=ok("ouigo.com"),
        ),
    ),
    (
        "n-leg-11",
        "sms",
        "commande",
        "Uber Eats : votre commande arrive dans 10 minutes. Suivez votre livreur dans l'application.",
    ),
    (
        "n-leg-12",
        "mail",
        "commande",
        mail(
            '"TotalEnergies" <service-client@totalenergies.fr>',
            "Votre facture d'électricité",
            "Bonjour,\nVotre facture de 64,20 € est disponible dans votre espace client. Elle sera prélevée le 28/10.",
            [],
            auth=ok("totalenergies.fr"),
        ),
    ),
    (
        "n-leg-13",
        "sms",
        "piege",
        "Veolia : un technicien passera relever votre compteur d'eau le 14/10 entre 8h et 12h. Merci de laisser l'accès libre.",
    ),
    (
        "n-leg-14",
        "mail",
        "officiel",
        mail(
            '"MGEN" <ne-pas-repondre@mgen.fr>',
            "Votre remboursement",
            "Bonjour,\nNous avons procédé au remboursement de 18,30 € pour vos soins du 01/10. Détail dans votre espace adhérent.",
            [],
            auth=ok("mgen.fr"),
        ),
    ),
    (
        "n-leg-15",
        "sms",
        "code",
        "Qonto : votre code de validation est 518 204. Ne le communiquez à personne, même à un conseiller Qonto.",
    ),
    ("n-leg-16", "sms", "code", "Instagram : 728 114 est votre code de connexion. Ne le partagez pas."),
    ("n-leg-17", "sms", "code", "Steam : votre code Steam Guard est F4K2Q."),
    ("n-leg-18", "sms", "banque", "Nickel : paiement de 23,40€ chez BOULANGERIE DU MARCHE accepté."),
    ("n-leg-19", "sms", "perso", "Urgent !! Le resto a avancé la réservation à 19h30, préviens les autres stp"),
    ("n-leg-20", "sms", "perso", "Maman, j'ai oublié mes clés, tu rentres à quelle heure ? 🙏"),
    ("n-leg-21", "sms", "perso", "Coucou, c'est Léa ! Merci encore pour le cadeau, ça m'a fait trop plaisir ❤️"),
    (
        "n-leg-22",
        "mail",
        "newsletter",
        mail(
            '"Disney+" <disneyplus@mail.disneyplus.com>',
            "Nouveau ce mois-ci sur Disney+",
            "Découvrez les nouveautés d'octobre. Ne manquez pas la nouvelle saison, disponible dès vendredi ! {0}",
            [("disneyplus.com", "https://www.disneyplus.com/fr-fr")],
            auth=ok("mail.disneyplus.com"),
            desinscription=True,
        ),
    ),
    (
        "n-leg-23",
        "mail",
        "newsletter",
        mail(
            '"Shein" <shein@email.shein.com>',
            "-20 % sur tout le site ce week-end",
            "Offre flash : -20 % sur tout le site jusqu'à dimanche minuit ! {0}",
            [("J'en profite", "https://fr.shein.com/")],
            auth=ok("email.shein.com"),
            desinscription=True,
        ),
    ),
    (
        "n-leg-24",
        "mail",
        "newsletter",
        mail(
            '"Canal+" <newsletter@canalplus.com>',
            "Le programme du week-end",
            "Votre sélection du week-end : films, séries et sport. {0}",
            [("canalplus.com", "https://www.canalplus.com/")],
            auth=ok("canalplus.com"),
            desinscription=True,
        ),
    ),
    (
        "n-leg-25",
        "sms",
        "piege",
        "Crous Bordeaux : votre état des lieux de sortie est confirmé le 30/10 à 10h. Pensez à rendre vos clés.",
    ),
    (
        "n-leg-26",
        "sms",
        "piege",
        "Bonjour, ici le garage Auto Plus, votre voiture est prête. Le montant est de 245€, payable au retrait.",
    ),
    (
        "n-leg-27",
        "mail",
        "piege",
        mail(
            '"Association des parents" <ape.ecole.jaures@googlemail.com>',
            "Vente de gâteaux - urgent besoin de bénévoles !",
            "Bonjour,\nNous manquons de bras pour la vente de gâteaux de vendredi. Si vous pouvez aider, répondez à ce mail. Merci !",
            [],
            auth=ok("googlemail.com"),
        ),
    ),
    (
        "n-leg-28",
        "sms",
        "piege",
        "Votre réservation au restaurant Le Chapon Fin ce soir 20h pour 4 personnes est confirmée.",
    ),
    (
        "n-leg-29",
        "mail",
        "officiel",
        mail(
            '"Île-de-France Mobilités" <ne-pas-repondre@iledefrance-mobilites.fr>',
            "Votre attestation Navigo",
            "Bonjour,\nVotre attestation annuelle Navigo est disponible dans votre espace personnel.",
            [],
            auth=ok("iledefrance-mobilites.fr"),
        ),
    ),
    (
        "n-leg-30",
        "sms",
        "livraison",
        "Votre colis Shein a été remis à La Poste. Suivi : https://www.laposte.fr/outils/suivre-vos-envois?code=LX123456789FR",
    ),
    (
        "n-leg-31",
        "mail",
        "commande",
        mail(
            '"Deliveroo" <noreply@deliveroo.fr>',
            "Votre reçu Deliveroo",
            "Merci pour votre commande ! Total : 24,50 €. À bientôt.",
            [],
            auth=ok("deliveroo.fr"),
        ),
    ),
    (
        "n-leg-32",
        "sms",
        "piege",
        "Bonjour, votre rendez-vous au centre de contrôle technique est confirmé le 17/10 à 8h30. En cas d'empêchement, appelez-nous.",
    ),
]
