"""C6 — Le presse-papiers : quand tu copies, et vers quelle appli tu vas ensuite (le « pont » A → B).

Jamais le contenu : seulement l'instant, l'appli de départ, la sorte (texte, adresse, image, fichier), la longueur et
une empreinte salée (pour reconnaître « la même chose » sans la garder). Ce que les gestionnaires de mots de passe
marquent comme secret ou éphémère est ignoré entièrement.
"""

from __future__ import annotations

from typing import Any

from modules.corvees.capteurs.base import Capteur
from modules.corvees.normalize import tok_pont

SECRETS = (
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "de.petermaurer.TransientPasteboardType",
)
ATTENTE_PONT_S = 120  # au-delà, une copie n'est plus reliée à l'appli suivante


def sorte(types: list[str]) -> str:
    if "public.file-url" in types:
        return "fichier"
    if "public.url" in types:
        return "url"
    if any(t in types for t in ("public.png", "public.tiff", "public.jpeg")):
        return "image"
    return "texte"


class PressePapiers(Capteur):
    nom = "pressepapiers"
    intervalle = 1.0

    def __init__(self, *args, apps=None, empreinte=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.apps = apps
        self.empreinte = empreinte or (lambda b: "")
        self.attente: tuple[float, str, dict[str, Any]] | None = None

    def demarrer(self) -> None:
        self.compteur = None
        if self.natif is None:
            self.desactiver("pas sur un Mac")
            return
        self.compteur = self.natif.compteur_presse_papiers()

    def relever(self, maintenant: float) -> None:
        if self.natif is None:
            return
        compteur = self.natif.compteur_presse_papiers()
        if compteur is None:
            self.degrader("macOS ne donne pas l'état du presse-papiers")
            return
        self.statut, self.detail = "ok", ""
        appli = getattr(self.apps, "courante", None) or ""
        if compteur != self.compteur:
            self.compteur = compteur
            self._nouvelle_copie(maintenant, appli)
        elif self.attente:
            debut, source, attrs = self.attente
            if appli and appli != source:
                self.emettre(maintenant, "clip", tok_pont(source, appli), destination=appli, **attrs)
                self.attente = None
            elif maintenant - debut > ATTENTE_PONT_S:
                self.attente = None

    def _nouvelle_copie(self, maintenant: float, appli: str) -> None:
        lu = self.natif.presse_papiers()
        if lu is None or not appli:
            self.attente = None
            return
        _, types, texte = lu
        if any(t in types for t in SECRETS):  # un mot de passe, un code : on n'en note rien du tout
            self.attente = None
            return
        attrs = {
            "source": appli,
            "type": sorte(types),
            "longueur": len(texte) if texte else 0,
            "empreinte": self.empreinte(texte) if texte else "",
        }
        self.emettre(maintenant, "copie", f"copie:{appli}", **attrs)
        self.attente = (maintenant, appli, attrs)
