"""Les services courants en France, choisis à la main : identifiant, nom, catégorie, domaines.

Les identifiants des marques reprennent ceux du détecteur d'arnaque (`arnaque/sosies.py`) : c'est ainsi qu'un
message « de ta banque X » est comparé à l'inventaire. Les liens de suppression et la double authentification ne
sont PAS écrits ici : ils viennent des bases ouvertes JustDeleteMe et 2factorauth (voir importer_bases.py).
"""

from __future__ import annotations

# (id, nom, catégorie, domaines). Le premier domaine sert à rapprocher les bases ouvertes.
SERVICES_FR: list[tuple[str, str, str, tuple[str, ...]]] = [
    # Comptes « maîtres »
    (
        "google",
        "Google (Gmail, YouTube)",
        "outils",
        ("google.com", "google.fr", "gmail.com", "youtube.com", "accounts.google.com"),
    ),
    ("apple", "Apple (identifiant Apple, iCloud)", "outils", ("apple.com", "icloud.com", "id.apple.com", "me.com")),
    (
        "microsoft",
        "Microsoft (Outlook, Office, Xbox)",
        "outils",
        (
            "microsoft.com",
            "live.com",
            "outlook.com",
            "hotmail.com",
            "hotmail.fr",
            "xbox.com",
            "office.com",
            "skype.com",
        ),
    ),
    (
        "amazon",
        "Amazon",
        "achats",
        (
            "amazon.fr",
            "amazon.com",
            "amazon.de",
            "amazon.es",
            "amazon.it",
            "amazon.co.uk",
            "audible.fr",
            "primevideo.com",
        ),
    ),
    ("yahoo", "Yahoo", "messagerie", ("yahoo.com", "yahoo.fr")),
    ("proton", "Proton (Proton Mail)", "messagerie", ("proton.me", "protonmail.com")),
    (
        "laposte",
        "La Poste (Colissimo, laposte.net)",
        "livraison",
        ("laposte.fr", "laposte.net", "colissimo.fr", "colissimo.com"),
    ),
    # Réseaux sociaux et messageries
    ("facebook", "Facebook", "réseaux sociaux", ("facebook.com", "facebookmail.com", "fb.com", "messenger.com")),
    ("instagram", "Instagram", "réseaux sociaux", ("instagram.com",)),
    ("twitter", "X (Twitter)", "réseaux sociaux", ("x.com", "twitter.com")),
    ("tiktok", "TikTok", "réseaux sociaux", ("tiktok.com",)),
    ("snapchat", "Snapchat", "réseaux sociaux", ("snapchat.com",)),
    ("linkedin", "LinkedIn", "emploi", ("linkedin.com",)),
    ("pinterest", "Pinterest", "réseaux sociaux", ("pinterest.com", "pinterest.fr")),
    ("reddit", "Reddit", "réseaux sociaux", ("reddit.com", "redditmail.com")),
    ("tumblr", "Tumblr", "réseaux sociaux", ("tumblr.com",)),
    ("threads", "Threads", "réseaux sociaux", ("threads.net", "threads.com")),
    ("bereal", "BeReal", "réseaux sociaux", ("bereal.com", "bere.al")),
    ("whatsapp", "WhatsApp", "messagerie", ("whatsapp.com",)),
    ("telegram", "Telegram", "messagerie", ("telegram.org",)),
    ("signal", "Signal", "messagerie", ("signal.org",)),
    ("discord", "Discord", "messagerie", ("discord.com", "discordapp.com")),
    # Outils
    ("dropbox", "Dropbox", "outils", ("dropbox.com", "dropboxmail.com")),
    ("adobe", "Adobe", "outils", ("adobe.com",)),
    ("canva", "Canva", "outils", ("canva.com",)),
    ("notion", "Notion", "outils", ("notion.so", "notion.com", "makenotion.com")),
    ("zoom", "Zoom", "outils", ("zoom.us", "zoom.com")),
    ("slack", "Slack", "outils", ("slack.com",)),
    ("github", "GitHub", "outils", ("github.com",)),
    ("openai", "OpenAI (ChatGPT)", "outils", ("openai.com", "chatgpt.com")),
    ("anthropic", "Claude (Anthropic)", "outils", ("anthropic.com", "claude.ai", "claude.com")),
    ("mozilla", "Compte Mozilla (Firefox)", "outils", ("mozilla.org", "firefox.com", "mozilla.com")),
    ("wetransfer", "WeTransfer", "outils", ("wetransfer.com",)),
    ("trello", "Trello", "outils", ("trello.com",)),
    ("evernote", "Evernote", "outils", ("evernote.com",)),
    ("lastpass", "LastPass", "outils", ("lastpass.com",)),
    ("bitwarden", "Bitwarden", "outils", ("bitwarden.com",)),
    ("onepassword", "1Password", "outils", ("1password.com",)),
    ("yuka", "Yuka", "outils", ("yuka.io",)),
    ("strava", "Strava", "loisirs", ("strava.com",)),
    ("garmin", "Garmin", "loisirs", ("garmin.com",)),
    ("withings", "Withings", "santé", ("withings.com",)),
    ("samsung", "Samsung", "outils", ("samsung.com",)),
    ("xiaomi", "Xiaomi", "outils", ("xiaomi.com", "mi.com")),
    ("huawei", "Huawei", "outils", ("huawei.com",)),
    # Achats
    ("cdiscount", "Cdiscount", "achats", ("cdiscount.com",)),
    ("fnac", "Fnac", "achats", ("fnac.com",)),
    ("darty", "Darty", "achats", ("darty.com",)),
    ("boulanger", "Boulanger", "achats", ("boulanger.com",)),
    ("leroymerlin", "Leroy Merlin", "achats", ("leroymerlin.fr",)),
    ("castorama", "Castorama", "achats", ("castorama.fr",)),
    ("ikea", "IKEA", "achats", ("ikea.com", "ikea.fr")),
    ("decathlon", "Decathlon", "achats", ("decathlon.fr", "decathlon.com")),
    ("zalando", "Zalando", "achats", ("zalando.fr", "zalando.com")),
    ("shein", "Shein", "achats", ("shein.com", "shein.fr")),
    ("aliexpress", "AliExpress", "achats", ("aliexpress.com",)),
    ("temu", "Temu", "achats", ("temu.com",)),
    ("ebay", "eBay", "achats", ("ebay.fr", "ebay.com")),
    ("rakuten", "Rakuten", "achats", ("rakuten.com", "fr.shopping.rakuten.com", "rakuten.fr")),
    ("backmarket", "Back Market", "achats", ("backmarket.fr", "backmarket.com")),
    ("veepee", "Veepee", "achats", ("veepee.fr", "vente-privee.com", "veepee.com")),
    ("showroomprive", "Showroomprivé", "achats", ("showroomprive.com",)),
    ("laredoute", "La Redoute", "achats", ("laredoute.fr",)),
    ("etsy", "Etsy", "achats", ("etsy.com",)),
    ("wish", "Wish", "achats", ("wish.com",)),
    ("carrefour", "Carrefour", "achats", ("carrefour.fr", "carrefour.com")),
    ("auchan", "Auchan", "achats", ("auchan.fr",)),
    ("leclerc", "E.Leclerc", "achats", ("e.leclerc", "leclercdrive.fr")),
    ("intermarche", "Intermarché", "achats", ("intermarche.com",)),
    ("lidl", "Lidl", "achats", ("lidl.fr", "lidl.com")),
    ("picard", "Picard", "achats", ("picard.fr",)),
    ("monoprix", "Monoprix", "achats", ("monoprix.fr",)),
    ("sephora", "Sephora", "achats", ("sephora.fr", "sephora.com")),
    ("nocibe", "Nocibé", "achats", ("nocibe.fr",)),
    ("kiabi", "Kiabi", "achats", ("kiabi.com",)),
    ("hm", "H&M", "achats", ("hm.com",)),
    ("zara", "Zara", "achats", ("zara.com",)),
    ("uniqlo", "Uniqlo", "achats", ("uniqlo.com",)),
    ("asos", "ASOS", "achats", ("asos.com",)),
    ("ldlc", "LDLC", "achats", ("ldlc.com",)),
    ("conforama", "Conforama", "achats", ("conforama.fr",)),
    ("but", "BUT", "achats", ("but.fr",)),
    ("maisonsdumonde", "Maisons du Monde", "achats", ("maisonsdumonde.com",)),
    ("cultura", "Cultura", "achats", ("cultura.com",)),
    ("vinted", "Vinted", "annonces", ("vinted.fr", "vinted.com")),
    ("leboncoin", "Leboncoin", "annonces", ("leboncoin.fr",)),
    # Repas et livraison
    ("ubereats", "Uber Eats", "repas", ("ubereats.com",)),
    ("deliveroo", "Deliveroo", "repas", ("deliveroo.fr", "deliveroo.com")),
    ("justeat", "Just Eat", "repas", ("just-eat.fr",)),
    ("toogoodtogo", "Too Good To Go", "repas", ("toogoodtogo.com", "toogoodtogo.fr")),
    ("hellofresh", "HelloFresh", "repas", ("hellofresh.fr", "hellofresh.com")),
    ("chronopost", "Chronopost", "livraison", ("chronopost.fr",)),
    ("mondialrelay", "Mondial Relay", "livraison", ("mondialrelay.fr", "mondialrelay.com")),
    ("ups", "UPS", "livraison", ("ups.com",)),
    ("dhl", "DHL", "livraison", ("dhl.com", "dhl.fr")),
    ("dpd", "DPD", "livraison", ("dpd.fr", "dpd.com")),
    # Banques, paiement, placements
    ("labanquepostale", "La Banque Postale", "banque", ("labanquepostale.fr",)),
    ("creditagricole", "Crédit Agricole", "banque", ("credit-agricole.fr", "ca-aquitaine.fr", "ca-paris.fr")),
    ("societegenerale", "Société Générale", "banque", ("societegenerale.fr", "societegenerale.com")),
    ("bnp", "BNP Paribas", "banque", ("bnpparibas.com", "bnpparibas.fr", "mabanque.bnpparibas")),
    ("lcl", "LCL", "banque", ("lcl.fr",)),
    ("caissedepargne", "Caisse d'Épargne", "banque", ("caisse-epargne.fr",)),
    ("banquepopulaire", "Banque Populaire", "banque", ("banquepopulaire.fr",)),
    ("creditmutuel", "Crédit Mutuel", "banque", ("creditmutuel.fr",)),
    ("cic", "CIC", "banque", ("cic.fr",)),
    ("boursobank", "Boursobank (Boursorama)", "banque", ("boursobank.com", "boursorama.com", "boursorama-banque.com")),
    ("hellobank", "Hello bank!", "banque", ("hellobank.fr",)),
    ("fortuneo", "Fortuneo", "banque", ("fortuneo.fr",)),
    ("monabanq", "Monabanq", "banque", ("monabanq.com",)),
    ("n26", "N26", "banque", ("n26.com",)),
    ("revolut", "Revolut", "banque", ("revolut.com",)),
    ("nickel", "Nickel", "banque", ("nickel.eu",)),
    ("qonto", "Qonto", "banque", ("qonto.com",)),
    ("shine", "Shine", "banque", ("shine.fr",)),
    ("mafrenchbank", "Ma French Bank", "banque", ("mafrenchbank.fr",)),
    ("paypal", "PayPal", "paiement", ("paypal.com", "paypal.fr")),
    ("lydia", "Lydia (Sumeria)", "paiement", ("lydia-app.com", "sumeria.eu")),
    ("sumup", "SumUp", "paiement", ("sumup.com", "sumup.fr")),
    ("traderepublic", "Trade Republic", "placements", ("traderepublic.com",)),
    ("degiro", "DEGIRO", "placements", ("degiro.fr", "degiro.com")),
    ("etoro", "eToro", "placements", ("etoro.com",)),
    ("coinbase", "Coinbase", "placements", ("coinbase.com",)),
    ("binance", "Binance", "placements", ("binance.com",)),
    ("kraken", "Kraken", "placements", ("kraken.com",)),
    ("bitpanda", "Bitpanda", "placements", ("bitpanda.com",)),
    ("yomoni", "Yomoni", "placements", ("yomoni.fr",)),
    ("linxea", "Linxea", "placements", ("linxea.com",)),
    # Santé
    ("ameli", "Ameli (Assurance Maladie)", "santé", ("ameli.fr", "assurance-maladie.fr")),
    ("doctolib", "Doctolib", "santé", ("doctolib.fr",)),
    ("monespacesante", "Mon espace santé", "santé", ("monespacesante.fr",)),
    ("alan", "Alan", "santé", ("alan.com", "alan.eu")),
    ("mgen", "MGEN", "santé", ("mgen.fr",)),
    ("harmoniemutuelle", "Harmonie Mutuelle", "santé", ("harmonie-mutuelle.fr",)),
    ("qare", "Qare", "santé", ("qare.fr",)),
    ("livi", "Livi", "santé", ("livi.fr",)),
    ("doctissimo", "Doctissimo", "santé", ("doctissimo.fr",)),
    # Administration
    ("impots", "impots.gouv (DGFiP)", "administration", ("impots.gouv.fr", "dgfip.finances.gouv.fr")),
    ("caf", "Caf", "administration", ("caf.fr",)),
    ("francetravail", "France Travail", "administration", ("francetravail.fr", "pole-emploi.fr")),
    ("ants", "ANTS", "administration", ("ants.gouv.fr",)),
    ("franceconnect", "FranceConnect", "administration", ("franceconnect.gouv.fr",)),
    ("servicepublic", "Service-Public", "administration", ("service-public.fr", "service-public.gouv.fr")),
    ("cpf", "Mon Compte Formation (CPF)", "administration", ("moncompteformation.gouv.fr",)),
    ("urssaf", "Urssaf", "administration", ("urssaf.fr",)),
    ("inforetraite", "Info Retraite", "administration", ("info-retraite.fr",)),
    ("msa", "MSA", "administration", ("msa.fr",)),
    ("antai", "ANTAI (amendes)", "administration", ("antai.gouv.fr", "amendes.gouv.fr")),
    ("critair", "Crit'Air", "administration", ("certificat-air.gouv.fr",)),
    # Télécoms et énergie
    ("orange", "Orange (Sosh)", "télécoms et énergie", ("orange.fr", "sosh.fr", "orange.com")),
    ("sfr", "SFR (RED by SFR)", "télécoms et énergie", ("sfr.fr", "red-by-sfr.fr")),
    ("free", "Free", "télécoms et énergie", ("free.fr", "free-mobile.fr")),
    ("bouygues", "Bouygues Telecom", "télécoms et énergie", ("bouyguestelecom.fr",)),
    ("edf", "EDF", "télécoms et énergie", ("edf.fr",)),
    ("engie", "Engie", "télécoms et énergie", ("engie.fr",)),
    ("totalenergies", "TotalEnergies", "télécoms et énergie", ("totalenergies.fr",)),
    ("ekwateur", "ekWateur", "télécoms et énergie", ("ekwateur.fr",)),
    ("veolia", "Veolia (eau)", "télécoms et énergie", ("veolia.fr", "eau.veolia.fr")),
    # Loisirs, vidéo, musique, lecture
    ("netflix", "Netflix", "loisirs", ("netflix.com",)),
    ("disney", "Disney+", "loisirs", ("disneyplus.com",)),
    ("canal", "Canal+", "loisirs", ("canalplus.com", "canal-plus.com", "mycanal.fr")),
    ("spotify", "Spotify", "loisirs", ("spotify.com",)),
    ("deezer", "Deezer", "loisirs", ("deezer.com",)),
    ("molotov", "Molotov", "loisirs", ("molotov.tv",)),
    ("paramountplus", "Paramount+", "loisirs", ("paramountplus.com",)),
    ("crunchyroll", "Crunchyroll", "loisirs", ("crunchyroll.com",)),
    ("twitch", "Twitch", "loisirs", ("twitch.tv",)),
    ("dazn", "DAZN", "loisirs", ("dazn.com",)),
    ("kobo", "Kobo", "loisirs", ("kobo.com",)),
    ("allocine", "AlloCiné", "loisirs", ("allocine.fr",)),
    ("senscritique", "SensCritique", "loisirs", ("senscritique.com",)),
    ("ticketmaster", "Ticketmaster", "loisirs", ("ticketmaster.fr",)),
    ("ugc", "UGC", "loisirs", ("ugc.fr",)),
    ("pathe", "Pathé", "loisirs", ("pathe.fr",)),
    # Jeux
    ("steam", "Steam", "jeux", ("steampowered.com", "steamcommunity.com")),
    ("epicgames", "Epic Games", "jeux", ("epicgames.com",)),
    ("playstation", "PlayStation", "jeux", ("playstation.com", "sonyentertainmentnetwork.com")),
    ("nintendo", "Nintendo", "jeux", ("nintendo.com", "nintendo.fr", "nintendo.net")),
    ("ubisoft", "Ubisoft", "jeux", ("ubisoft.com",)),
    ("ea", "EA", "jeux", ("ea.com",)),
    ("blizzard", "Blizzard (Battle.net)", "jeux", ("blizzard.com", "battle.net")),
    ("riot", "Riot Games", "jeux", ("riotgames.com",)),
    ("roblox", "Roblox", "jeux", ("roblox.com",)),
    ("fdj", "FDJ", "jeux", ("fdj.fr",)),
    ("pmu", "PMU", "jeux", ("pmu.fr",)),
    ("winamax", "Winamax", "jeux", ("winamax.fr",)),
    ("betclic", "Betclic", "jeux", ("betclic.fr",)),
    # Voyages et transport
    ("sncf", "SNCF Connect", "voyages et transport", ("sncf-connect.com", "sncf.com", "sncf.fr", "oui.sncf")),
    ("ouigo", "Ouigo", "voyages et transport", ("ouigo.com",)),
    ("trainline", "Trainline", "voyages et transport", ("trainline.fr", "thetrainline.com", "trainline.com")),
    ("blablacar", "BlaBlaCar", "voyages et transport", ("blablacar.fr", "blablacar.com")),
    ("airbnb", "Airbnb", "voyages et transport", ("airbnb.fr", "airbnb.com")),
    ("booking", "Booking.com", "voyages et transport", ("booking.com",)),
    ("abritel", "Abritel", "voyages et transport", ("abritel.fr",)),
    ("expedia", "Expedia", "voyages et transport", ("expedia.fr", "expedia.com")),
    ("hotelscom", "Hotels.com", "voyages et transport", ("hotels.com",)),
    ("tripadvisor", "Tripadvisor", "voyages et transport", ("tripadvisor.fr", "tripadvisor.com")),
    ("easyjet", "easyJet", "voyages et transport", ("easyjet.com",)),
    ("ryanair", "Ryanair", "voyages et transport", ("ryanair.com",)),
    ("airfrance", "Air France", "voyages et transport", ("airfrance.fr", "airfrance.com")),
    ("transavia", "Transavia", "voyages et transport", ("transavia.com",)),
    ("uber", "Uber", "voyages et transport", ("uber.com",)),
    ("bolt", "Bolt", "voyages et transport", ("bolt.eu",)),
    ("heetch", "Heetch", "voyages et transport", ("heetch.com",)),
    ("getaround", "Getaround", "voyages et transport", ("getaround.com",)),
    ("flixbus", "FlixBus", "voyages et transport", ("flixbus.fr", "flixbus.com")),
    ("lime", "Lime", "voyages et transport", ("li.me",)),
    # Emploi
    ("indeed", "Indeed", "emploi", ("indeed.fr", "indeed.com")),
    ("welcometothejungle", "Welcome to the Jungle", "emploi", ("welcometothejungle.com",)),
    ("malt", "Malt", "emploi", ("malt.fr", "malt.com")),
    ("hellowork", "HelloWork", "emploi", ("hellowork.com",)),
    ("apec", "Apec", "emploi", ("apec.fr",)),
    # Rencontres
    ("tinder", "Tinder", "rencontres", ("tinder.com", "gotinder.com")),
    ("meetic", "Meetic", "rencontres", ("meetic.fr",)),
    ("bumble", "Bumble", "rencontres", ("bumble.com",)),
    ("happn", "happn", "rencontres", ("happn.com",)),
    ("hinge", "Hinge", "rencontres", ("hinge.co",)),
    # Presse
    ("lemonde", "Le Monde", "presse", ("lemonde.fr",)),
    ("lefigaro", "Le Figaro", "presse", ("lefigaro.fr",)),
    ("liberation", "Libération", "presse", ("liberation.fr",)),
    ("mediapart", "Mediapart", "presse", ("mediapart.fr",)),
    ("sudouest", "Sud Ouest", "presse", ("sudouest.fr",)),
    ("ouestfrance", "Ouest-France", "presse", ("ouest-france.fr",)),
    ("leparisien", "Le Parisien", "presse", ("leparisien.fr",)),
    ("lequipe", "L'Équipe", "presse", ("lequipe.fr",)),
    # Éducation et cagnottes
    ("duolingo", "Duolingo", "éducation", ("duolingo.com",)),
    ("babbel", "Babbel", "éducation", ("babbel.com",)),
    ("openclassrooms", "OpenClassrooms", "éducation", ("openclassrooms.com",)),
    ("coursera", "Coursera", "éducation", ("coursera.org",)),
    ("udemy", "Udemy", "éducation", ("udemy.com",)),
    ("leetchi", "Leetchi", "paiement", ("leetchi.com",)),
    ("ulule", "Ulule", "paiement", ("ulule.com",)),
    ("kisskissbankbank", "KissKissBankBank", "paiement", ("kisskissbankbank.com",)),
    # Autres services très utilisés en France (liens de suppression présents dans JustDeleteMe)
    ("wikipedia", "Wikipédia", "outils", ("wikipedia.org",)),
    ("vimeo", "Vimeo", "loisirs", ("vimeo.com",)),
    ("dailymotion", "Dailymotion", "loisirs", ("dailymotion.com",)),
    ("soundcloud", "SoundCloud", "loisirs", ("soundcloud.com",)),
    ("shazam", "Shazam", "loisirs", ("shazam.com",)),
    ("quora", "Quora", "réseaux sociaux", ("quora.com",)),
    ("medium", "Medium", "presse", ("medium.com",)),
    ("flickr", "Flickr", "loisirs", ("flickr.com",)),
    ("wattpad", "Wattpad", "loisirs", ("wattpad.com",)),
    ("tidal", "TIDAL", "loisirs", ("tidal.com",)),
    ("qobuz", "Qobuz", "loisirs", ("qobuz.com",)),
    ("bluesky", "Bluesky", "réseaux sociaux", ("bsky.app",)),
    ("mastodon", "Mastodon (mastodon.social)", "réseaux sociaux", ("mastodon.social",)),
    ("viber", "Viber", "messagerie", ("viber.com",)),
    ("wordpresscom", "WordPress.com", "outils", ("wordpress.com",)),
    ("wix", "Wix", "outils", ("wix.com",)),
    ("ovhcloud", "OVHcloud", "outils", ("ovhcloud.com", "ovh.com")),
    ("doodle", "Doodle", "outils", ("doodle.com",)),
    ("todoist", "Todoist", "outils", ("todoist.com",)),
    ("feedly", "Feedly", "outils", ("feedly.com",)),
    ("deepl", "DeepL", "outils", ("deepl.com",)),
    ("grammarly", "Grammarly", "outils", ("grammarly.com",)),
    ("dashlane", "Dashlane", "outils", ("dashlane.com",)),
    ("nordvpn", "NordVPN", "outils", ("nordvpn.com",)),
    ("surfshark", "Surfshark", "outils", ("surfshark.com",)),
    ("mega", "MEGA", "outils", ("mega.nz", "mega.io")),
    ("pcloud", "pCloud", "outils", ("pcloud.com",)),
    ("waze", "Waze", "voyages et transport", ("waze.com",)),
    ("komoot", "Komoot", "loisirs", ("komoot.com",)),
    ("myfitnesspal", "MyFitnessPal", "santé", ("myfitnesspal.com",)),
    ("headspace", "Headspace", "santé", ("headspace.com",)),
    ("flo", "Flo", "santé", ("flo.health",)),
    ("clue", "Clue", "santé", ("helloclue.com",)),
    ("goodreads", "Goodreads", "loisirs", ("goodreads.com",)),
    ("imdb", "IMDb", "loisirs", ("imdb.com",)),
    ("letterboxd", "Letterboxd", "loisirs", ("letterboxd.com",)),
    ("chesscom", "Chess.com", "jeux", ("chess.com",)),
    ("lichess", "Lichess", "jeux", ("lichess.org",)),
    ("geocaching", "Geocaching", "loisirs", ("geocaching.com",)),
    ("okcupid", "OkCupid", "rencontres", ("okcupid.com",)),
    ("badoo", "Badoo", "rencontres", ("badoo.com",)),
    ("patreon", "Patreon", "paiement", ("patreon.com",)),
    ("wise", "Wise", "paiement", ("wise.com",)),
    ("depop", "Depop", "annonces", ("depop.com",)),
    ("nike", "Nike", "achats", ("nike.com",)),
    ("glassdoor", "Glassdoor", "emploi", ("glassdoor.fr", "glassdoor.com")),
]
