"""200 façons de dire ce qu'on a dans le frigo (§10.3) : pluriels, accents oubliés, majuscules, fautes courantes,
quantités en chiffres ou en lettres, unités, contenants, restes, synonymes, petits mots autour.

Chaque ligne : (ce que tu écris, identifiant attendu, quantité attendue dans l'unité de l'ingrédient ou None).
Quantité None : non dite, ou un reste (« assez »). Un contenant compte pour son format le plus courant (« un paquet
de lardons » : 200 g), une pièce pour son poids moyen quand l'ingrédient se compte en grammes (« une patate » : 150 g).
"""

from __future__ import annotations

FORMULATIONS: list[tuple[str, str, float | None]] = [
    # --- Pluriels, accents, majuscules ---
    ("courgettes", "courgette", None),
    ("Courgette", "courgette", None),
    ("COURGETTES", "courgette", None),
    ("oeufs", "oeuf", None),
    ("œufs", "oeuf", None),
    ("Oeuf", "oeuf", None),
    ("tomates", "tomate", None),
    ("poireaux", "poireau", None),
    ("carottes", "carotte", None),
    ("oignons", "oignon", None),
    ("échalotes", "echalote", None),
    ("echalotes", "echalote", None),
    ("épinards", "epinard", None),
    ("epinards", "epinard", None),
    ("aubergines", "aubergine", None),
    ("poivrons", "poivron", None),
    ("champignons", "champignon", None),
    ("brocolis", "brocoli", None),
    ("concombres", "concombre", None),
    ("citrons", "citron", None),
    ("avocats", "avocat", None),
    ("pommes", "pomme", None),
    ("navets", "navet", None),
    ("radis", "radis", None),
    ("endives", "endive", None),
    ("betteraves", "betterave", None),
    ("panais", "panais", None),
    ("fenouil", "fenouil", None),
    ("céleri-rave", "celeri_rave", None),
    ("chou-fleur", "chou_fleur", None),
    ("chou fleur", "chou_fleur", None),
    ("choux de Bruxelles", "chou_bruxelles", None),
    ("patates douces", "patate_douce", None),
    ("pommes de terre", "pomme_de_terre", None),
    ("pomme de terre", "pomme_de_terre", None),
    ("haricots verts", "haricot_vert", None),
    ("petits pois", "petit_pois", None),
    ("lentilles corail", "lentille_corail", None),
    ("lentilles vertes", "lentille_verte", None),
    ("pois chiches", "pois_chiche", None),
    # --- Synonymes ---
    ("patates", "pomme_de_terre", None),
    ("une patate", "pomme_de_terre", 150),
    ("pdt", "pomme_de_terre", None),
    ("steak haché", "boeuf_hache", None),
    ("steaks hachés", "boeuf_hache", None),
    ("viande hachée", "boeuf_hache", None),
    ("crème", "creme", None),
    ("crème liquide", "creme", None),
    ("crème fraîche", "creme_epaisse", None),
    ("creme fraiche", "creme_epaisse", None),
    ("crème épaisse", "creme_epaisse", None),
    ("fromage râpé", "fromage_rape", None),
    ("gruyère", "fromage_rape", None),
    ("emmental", "fromage_rape", None),
    ("yaourt grec", "yaourt_grec", None),
    ("yaourts", "yaourt_grec", None),
    ("fromage blanc", "yaourt_grec", None),
    ("blancs de poulet", "poulet_filet", None),
    ("escalopes de poulet", "poulet_filet", None),
    ("poulet", "poulet_filet", None),
    ("cuisses de poulet", "poulet_cuisse", None),
    ("chipolatas", "saucisse", None),
    ("saucisses", "saucisse", None),
    ("bacon", "lardons", None),
    ("lardons", "lardons", None),
    ("jambon blanc", "jambon", None),
    ("tranches de jambon", "jambon", None),
    ("cabillaud", "poisson_blanc", None),
    ("colin", "poisson_blanc", None),
    ("miettes de thon", "thon", None),
    ("thon en boîte", "thon", None),
    ("mozza", "mozzarella", None),
    ("chèvre", "chevre", None),
    ("fromage de chèvre", "chevre", None),
    ("féta", "feta", None),
    ("philadelphia", "fromage_frais", None),
    ("saint moret", "fromage_frais", None),
    ("butternut", "courge", None),
    ("potiron", "courge", None),
    ("potimarron", "courge", None),
    ("spaghetti", "pates", None),
    ("coquillettes", "pates", None),
    ("penne", "pates", None),
    ("riz basmati", "riz", None),
    ("wraps", "tortilla", None),
    ("baguette", "pain", None),
    ("pain rassis", "pain", None),
    ("lait de coco", "lait_coco", None),
    ("laitue", "salade", None),
    ("batavia", "salade", None),
    ("maïs", "mais", None),
    ("olives", "olive", None),
    ("champis", "champignon", None),
    ("gousses d'ail", "ail", None),
    ("ail", "ail", None),
    ("persil", "persil", None),
    ("coriandre", "coriandre", None),
    ("basilic frais", "basilic", None),
    ("houmous", "houmous", None),
    ("hoummous", "houmous", None),
    # --- Fautes courantes ---
    ("courgete", "courgette", None),
    ("courgetes", "courgette", None),
    ("tomatte", "tomate", None),
    ("ognon", "oignon", None),
    ("ognons", "oignon", None),
    ("carrotte", "carotte", None),
    ("champignions", "champignon", None),
    ("brocolli", "brocoli", None),
    ("aubergine", "aubergine", None),
    ("poivon", "poivron", None),
    ("épinars", "epinard", None),
    ("poireux", "poireau", None),
    ("concombe", "concombre", None),
    ("mozarella", "mozzarella", None),
    ("parmesant", "parmesan", None),
    ("jambom", "jambon", None),
    ("saucise", "saucisse", None),
    ("yahourt grec", "yaourt_grec", None),
    ("lardon", "lardons", None),
    ("pomme de tere", "pomme_de_terre", None),
    ("bananes", "", None),  # inconnue de la base : rien ne doit être inventé
    ("avocas", "avocat", None),
    ("citrom", "citron", None),
    ("fetta", "feta", None),
    ("chorizzo", "chorizo", None),
    ("ricota", "ricotta", None),
    # --- Quantités en chiffres et unités ---
    ("2 courgettes", "courgette", 2),
    ("3 tomates", "tomate", 3),
    ("6 oeufs", "oeuf", 6),
    ("12 œufs", "oeuf", 12),
    ("1 oignon", "oignon", 1),
    ("4 carottes", "carotte", 4),
    ("2 poivrons", "poivron", 2),
    ("500g de steak haché", "boeuf_hache", 500),
    ("500 g de steak haché", "boeuf_hache", 500),
    ("250 g de lardons", "lardons", 250),
    ("200g de feta", "feta", 200),
    ("1 kg de pommes de terre", "pomme_de_terre", 1000),
    ("1,5 kg de pommes de terre", "pomme_de_terre", 1500),
    ("1.5kg de patates", "pomme_de_terre", 1500),
    ("400 g de poulet", "poulet_filet", 400),
    ("300gr de champignons", "champignon", 300),
    ("20 cl de crème", "creme", 200),
    ("200 ml de crème", "creme", 200),
    ("1 l de lait", "lait", 1000),
    ("1 litre de lait", "lait", 1000),
    ("50 cl de lait", "lait", 500),
    ("100 g de parmesan", "parmesan", 100),
    ("150 grammes de chèvre", "chevre", 150),
    ("2 kilos de pommes", "pomme", 2000 / 170),  # pommes en pièces : 2 kg à 170 g la pomme
    ("½ citron", "citron", 0.5),
    ("1/2 chou-fleur", "chou_fleur", 0.5),
    ("1/2 concombre", "concombre", 0.5),
    ("2 avocats", "avocat", 2),
    ("3 pavés de saumon", "saumon", 3),
    ("2 escalopes de dinde", "dinde", 260),
    # --- Quantités en lettres ---
    ("une courgette", "courgette", 1),
    ("deux courgettes", "courgette", 2),
    ("trois tomates", "tomate", 3),
    ("quatre œufs", "oeuf", 4),
    ("six oeufs", "oeuf", 6),
    ("une douzaine d'œufs", "oeuf", 12),
    ("deux douzaines d'oeufs", "oeuf", 24),
    ("une demi courgette", "courgette", 0.5),
    ("un demi oignon", "oignon", 0.5),
    ("une demi-baguette", "pain", 0.5),
    ("un oignon et demi", "oignon", 1.5),
    ("un litre et demi de lait", "lait", 1500),
    ("cinq carottes", "carotte", 5),
    ("un poivron", "poivron", 1),
    ("un avocat", "avocat", 1),
    ("une aubergine", "aubergine", 1),
    ("deux poireaux", "poireau", 2),
    ("trois pommes de terre", "pomme_de_terre", 450),  # en grammes : 150 g la pomme de terre
    # --- Contenants ---
    ("une brique de crème", "creme", 200),
    ("2 briques de crème", "creme", 400),
    ("une boîte de thon", "thon", 140),
    ("2 boîtes de thon", "thon", 280),
    ("une botte de coriandre", "coriandre", 30),
    ("une demi botte de persil", "persil", 15),
    ("un paquet de lardons", "lardons", 200),
    ("un pot de yaourt grec", "yaourt_grec", 500),
    ("une boule de mozzarella", "mozzarella", 1),
    ("un bloc de feta", "feta", 200),
    ("une boîte de pois chiches", "pois_chiche", 265),
    ("un sachet d'épinards", "epinard", 400),
    # --- Restes et petits mots ---
    ("reste de riz", "riz", None),
    ("un reste de riz", "riz", None),
    ("des restes de poulet", "poulet_filet", None),
    ("un fond de crème", "creme", None),
    ("un bout de chorizo", "chorizo", None),
    ("un reste de pâtes", "pates", None),
    ("j'ai encore du jambon", "jambon", None),
    ("il me reste des carottes", "carotte", None),
    ("du fromage râpé", "fromage_rape", None),
    ("de la feta", "feta", None),
    ("des œufs", "oeuf", None),
    ("quelques tomates", "tomate", None),
    ("un peu de parmesan", "parmesan", None),
    ("mes courgettes", "courgette", None),
    ("encore 2 courgettes", "courgette", 2),
    ("des tomates cerises", "tomate_cerise", None),
    ("tomates cerise", "tomate_cerise", None),
]
